## 1. Using KNN, (assuming K=2,3,4,5), classify point (50,40) and point (30,40), whether it belongs to class 1 or class 2.

In [7]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
test_data= pd.read_csv('test_new.csv')
train_data = pd.read_csv('train_new.csv')

In [9]:

df1=test_data
df2=train_data


In [10]:
df1.head()

dvcat    weight   dead  airbag seatbelt  frontal sex  ageOFocc  yearacc  \
0  40-54    18.895  alive  airbag   belted        0   m        25     2002   
1  25-39   266.532  alive    none     none        1   f        28     2001   
2  25-39    51.810  alive  airbag   belted        1   f        36     1999   
3  10-24  1567.626  alive  airbag   belted        0   f        24     2002   
4  25-39    31.342  alive    none     none        1   f        46     1997   

   yearVeh     abcat occRole  deploy   caseid  
0   2000.0    deploy    pass       1  81:99:1  
1   1991.0   unavail  driver       0  76:12:2  
2   1994.0    deploy  driver       1  78:53:2  
3   1994.0  nodeploy  driver       0  11:47:1  
4   1990.0   unavail    pass       0  12:87:2

In [11]:
df2.head()


dvcat   weight   dead  airbag seatbelt  frontal sex  ageOFocc  yearacc  \
0    55+   53.342   dead  airbag   belted        1   f        48     2002   
1  25-39  154.960  alive    none     none        1   m        26     2001   
2    55+   38.994  alive    none     none        1   f        51     2002   
3  25-39  168.568  alive  airbag   belted        1   m        27     1998   
4  10-24   27.751  alive  airbag   belted        0   m        26     2002   

   yearVeh     abcat occRole  deploy    caseid  injSeverity  
0     1997    deploy  driver       1  45:150:1            3  
1     1968   unavail  driver       0   76:40:1            3  
2     1994   unavail  driver       0  11:184:1            3  
3     1996    deploy    pass       1    9:17:1            3  
4     1997  nodeploy    pass       0     2:2:2            0

In [12]:
from sklearn.preprocessing import LabelEncoder
t= LabelEncoder()
df1["airbag"]=t.fit_transform(df1["airbag"])
df1["seatbelt"]=t.fit_transform(df1["seatbelt"])
df1["sex"]=t.fit_transform(df1["sex"])
from sklearn.preprocessing import LabelEncoder
u= LabelEncoder()
df2["airbag"]=u.fit_transform(df2["airbag"])
df2["seatbelt"]=u.fit_transform(df2["seatbelt"])
df2["sex"]=u.fit_transform(df2["sex"])
features_train = list(['airbag','seatbelt','sex'])
train_x = train_data[features_train].values
train_x

array([[0, 0, 0],
       [1, 1, 1],
       [1, 1, 0],
       ...,
       [0, 0, 0],
       [1, 1, 0],
       [1, 0, 1]])

In [13]:
target_train = list(['dead']) 
train_y = train_data[target_train].values
features_test = list(['airbag','seatbelt','sex'])
test_x = test_data[features_test].values
target_test = list(['dead'])
test_y= test_data[target_test].values
df1['dead']=df1['dead'].map({'alive':0,'dead':1})
df2['dead']=df1['dead'].map({'alive':0,'dead':1})
df2.head()

dvcat   weight  dead  airbag  seatbelt  frontal  sex  ageOFocc  yearacc  \
0    55+   53.342   NaN       0         0        1    0        48     2002   
1  25-39  154.960   NaN       1         1        1    1        26     2001   
2    55+   38.994   NaN       1         1        1    0        51     2002   
3  25-39  168.568   NaN       0         0        1    1        27     1998   
4  10-24   27.751   NaN       0         0        0    1        26     2002   

   yearVeh     abcat occRole  deploy    caseid  injSeverity  
0     1997    deploy  driver       1  45:150:1            3  
1     1968   unavail  driver       0   76:40:1            3  
2     1994   unavail  driver       0  11:184:1            3  
3     1996    deploy    pass       1    9:17:1            3  
4     1997  nodeploy    pass       0     2:2:2            0

In [14]:
scaler = StandardScaler()

In [15]:

# fit training set
scaler.fit(train_x)
StandardScaler()
# apply transform for both test and training sets
train_x = scaler.transform(train_x)
test_x = scaler.transform(test_x)
# logistic model
logistic=LogisticRegression()
# fit values for x and y
logistic.fit(train_x,train_y)


C:\Users\91830\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [16]:
# prediction from test data
prediction=logistic.predict(test_x)
# confusion matrix 
confusion_matrix=confusion_matrix(prediction,test_y)
print(confusion_matrix)

[[8249  403]
 [   0    0]]


In [17]:
# calculating accuracy
accuracy_score=accuracy_score(prediction,test_y)
print(accuracy_score)
0.9534211742949606
# print misclassified values from predicton
print('Misclassified sample : %d '%(test_y !=prediction).sum())


0.9534211742949606
Misclassified sample : 3486756 


## K=2

In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=2)
from sklearn.metrics import accuracy_score,confusion_matrix
confusion_matrix = confusion_matrix(test_y, prediction)
print("\t","Predicted values")
print("Original values","\n",confusion_matrix)



	 Predicted values
Original values 
 [[8249    0]
 [ 403    0]]


In [20]:
print('Misclassified samples: %d' % (test_x != prediction))
# effect of x value on classifier
Misclassified_sample=[]

Misclassified samples: 1


C:\Users\91830\AppData\Local\Temp\ipykernel_12380\1481535045.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print('Misclassified samples: %d' % (test_x != prediction))


In [21]:
# claculating error for k values 
for i in range(1,20):
 knn=KNeighborsClassifier(n_neighbors=i)
 knn.fit(train_x,train_y)
 pred=knn.predict(test_x)
 Misclassified_sample.append(test_y !=pred)
print(Misclassified_sample)

C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

[array([[False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [ True,  True, False, ...,  True,  True,  True]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True,  True,  True, ...,  True,  True,  True]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       

## K=3

In [22]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
from sklearn.metrics import accuracy_score,confusion_matrix
confusion_matrix = confusion_matrix(test_y, prediction)
print("\t","Predicted values")
print("Original values","\n",confusion_matrix)

	 Predicted values
Original values 
 [[8249    0]
 [ 403    0]]


In [23]:
print('Misclassified samples: %d' % (test_x != prediction))
# effect of x value on classifier
Misclassified_sample=[]


Misclassified samples: 1


C:\Users\91830\AppData\Local\Temp\ipykernel_12380\4027423056.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print('Misclassified samples: %d' % (test_x != prediction))


In [24]:
# claculating error for k values 
for i in range(1,20):
 knn=KNeighborsClassifier(n_neighbors=i)
 knn.fit(train_x,train_y)
 pred=knn.predict(test_x)
 Misclassified_sample.append(test_y !=pred)
print(Misclassified_sample)

C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

[array([[False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [ True,  True, False, ...,  True,  True,  True]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True,  True,  True, ...,  True,  True,  True]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       

## K=4

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=4)
from sklearn.metrics import accuracy_score,confusion_matrix
confusion_matrix = confusion_matrix(test_y, prediction)
print("\t","Predicted values")
print("Original values","\n",confusion_matrix)

	 Predicted values
Original values 
 [[8249    0]
 [ 403    0]]


In [26]:
print('Misclassified samples: %d' % (test_x != prediction))
# effect of x value on classifier
Misclassified_sample=[]

Misclassified samples: 1


C:\Users\91830\AppData\Local\Temp\ipykernel_12380\1481535045.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print('Misclassified samples: %d' % (test_x != prediction))


In [27]:
# claculating error for k values 
for i in range(1,20):
 knn=KNeighborsClassifier(n_neighbors=i)
 knn.fit(train_x,train_y)
 pred=knn.predict(test_x)
 Misclassified_sample.append(test_y !=pred)
print(Misclassified_sample)

C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

[array([[False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [ True,  True, False, ...,  True,  True,  True]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True,  True,  True, ...,  True,  True,  True]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       

## K=5

In [28]:
print('Misclassified samples: %d' % (test_x != prediction))
# effect of x value on classifier
Misclassified_sample=[]


Misclassified samples: 1


C:\Users\91830\AppData\Local\Temp\ipykernel_12380\4027423056.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print('Misclassified samples: %d' % (test_x != prediction))


In [29]:
# claculating error for k values 
for i in range(1,20):
 knn=KNeighborsClassifier(n_neighbors=i)
 knn.fit(train_x,train_y)
 pred=knn.predict(test_x)
 Misclassified_sample.append(test_y !=pred)
print(Misclassified_sample)


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

[array([[False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [ True,  True, False, ...,  True,  True,  True]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [ True,  True,  True, ...,  True,  True,  True]]), array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       

## 2.Now, again use your ‘crashTest.csv’ file and build a classifier model using both Logistic regression and KNN.

In [52]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
df=pd.read_csv('train_new.csv')
df.head()


dvcat   weight   dead  airbag seatbelt  frontal sex  ageOFocc  yearacc  \
0    55+   53.342   dead  airbag   belted        1   f        48     2002   
1  25-39  154.960  alive    none     none        1   m        26     2001   
2    55+   38.994  alive    none     none        1   f        51     2002   
3  25-39  168.568  alive  airbag   belted        1   m        27     1998   
4  10-24   27.751  alive  airbag   belted        0   m        26     2002   

   yearVeh     abcat occRole  deploy    caseid  injSeverity  
0     1997    deploy  driver       1  45:150:1            3  
1     1968   unavail  driver       0   76:40:1            3  
2     1994   unavail  driver       0  11:184:1            3  
3     1996    deploy    pass       1    9:17:1            3  
4     1997  nodeploy    pass       0     2:2:2            0

In [50]:
df['dvcat'].unique()

array([4, 2, 1, 3, 0], dtype=int64)

In [53]:

df['dvcat']=df['dvcat'].map({'1-9km/h':0,'10-24':1,'25-39':2,'40-54':3,'55+':4})
df['dead']=df['dead'].map({'dead':0,'alive':1})
df['airbag']= df['airbag'].map({'airbag':1,'none':0})
df['seatbelt']=df['seatbelt'].map({'none':0,'belted':1})
df['sex']=df['sex'].map({'m':0,'f':1})
df['abcat']=df['abcat'].map({'unavail':0,'deploy':1,'nodeploy':2})
df['occRole']=df['occRole'].map({'pass':0,'driver':1})
df = df.drop(['caseid'],axis=1)
k = list(df.columns)
features = list(set(k)-set(['injSeverity']))
output = list(['injSeverity'])
x = df.loc[:,features]
y = df.loc[:,output]
X_train,X_test,y_train,y_test =train_test_split(x,y,test_size=0.3,random_state=0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) 
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski', p=2)
model = knn.fit(X_train,y_train)

C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [54]:
y_pred = knn.predict(X_test)
print(y_pred)

[1 2 3 ... 1 0 1]


In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
# trying for best fit of k values
for i in range(1,100):
 knn = KNeighborsClassifier(n_neighbors=i)
 knn.fit(X_train,y_train)
 pred_i = knn.predict(X_test)
 print(i)
 print(pred_i) 
 print(accuracy_score(y_test,pred_i))


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


1
[1 2 2 ... 3 0 1]
0.37703984819734343


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


2
[1 2 0 ... 1 0 1]
0.34497153700189753


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


3
[1 2 0 ... 1 0 3]
0.3918406072106262


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


4
[1 2 0 ... 1 0 1]
0.4


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


5
[1 2 3 ... 1 0 1]
0.40132827324478176


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


6
[1 3 2 ... 1 3 1]
0.40436432637571157


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


7
[1 2 3 ... 1 0 3]
0.41840607210626185


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


8
[1 2 3 ... 1 0 3]
0.42182163187855787


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


9
[1 3 3 ... 1 0 3]
0.43111954459203033


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


10
[1 3 3 ... 1 0 3]
0.4318785578747628


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


11
[1 2 3 ... 1 0 3]
0.43662239089184063


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


12
[1 2 3 ... 1 0 3]
0.43795066413662237


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


13
[1 3 3 ... 1 0 3]
0.44003795066413665


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


14
[1 3 3 ... 1 0 3]
0.43586337760910815


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


15
[1 3 3 ... 1 0 3]
0.4381404174573055


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


16
[1 3 3 ... 3 0 1]
0.4425047438330171


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


17
[1 3 3 ... 3 0 1]
0.4409867172675522


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


18
[1 2 3 ... 3 0 1]
0.44041745730550286


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


19
[1 2 3 ... 3 0 1]
0.4409867172675522


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


20
[1 2 3 ... 3 0 1]
0.43870967741935485


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


21
[1 2 3 ... 3 0 1]
0.4442125237191651


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


22
[1 2 3 ... 3 0 1]
0.4464895635673624


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


23
[1 2 3 ... 3 0 1]
0.4476280834914611


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


24
[1 2 3 ... 3 0 1]
0.44516129032258067


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


25
[1 2 3 ... 3 0 1]
0.44516129032258067


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


26
[1 3 3 ... 3 0 1]
0.4453510436432638


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


27
[1 3 3 ... 3 0 1]
0.4478178368121442


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


28
[1 3 3 ... 3 0 1]
0.4468690702087287


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


29
[1 3 3 ... 3 0 3]
0.44857685009487663


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


30
[1 3 3 ... 3 0 3]
0.4506641366223909


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


31
[1 3 3 ... 3 0 3]
0.44990512333965843


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


32
[1 3 3 ... 3 0 3]
0.450853889943074


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


33
[1 3 3 ... 3 0 3]
0.45142314990512333


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


34
[1 3 3 ... 3 0 3]
0.4521821631878558


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


35
[1 3 3 ... 3 0 3]
0.4510436432637571


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


36
[1 3 3 ... 3 0 3]
0.45142314990512333


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


37
[1 3 3 ... 3 0 3]
0.44990512333965843


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


38
[1 3 3 ... 3 0 3]
0.4523719165085389


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


39
[1 3 3 ... 3 0 3]
0.45502846299810246


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


40
[1 3 3 ... 3 0 3]
0.4540796963946869


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


41
[1 3 3 ... 3 0 3]
0.45483870967741935


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


42
[1 3 3 ... 3 0 3]
0.45749525616698294


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


43
[1 3 3 ... 3 0 3]
0.4573055028462998


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


44
[1 3 3 ... 3 0 3]
0.45825426944971537


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


45
[1 3 3 ... 3 0 3]
0.45673624288425047


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


46
[1 3 3 ... 3 0 3]
0.45692599620493357


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


47
[1 3 3 ... 3 0 3]
0.45787476280834916


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


48
[1 3 3 ... 3 0 3]
0.45977229601518027


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


49
[1 3 3 ... 1 0 3]
0.4590132827324478


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


50
[1 3 3 ... 1 0 3]
0.4573055028462998


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


51
[1 3 3 ... 1 0 3]
0.46091081593927896


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


52
[1 3 3 ... 1 0 3]
0.4586337760910816


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


53
[1 3 3 ... 1 3 3]
0.4586337760910816


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


54
[1 2 3 ... 3 3 3]
0.45502846299810246


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


55
[1 2 3 ... 3 3 3]
0.45464895635673624


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


56
[3 2 3 ... 3 3 3]
0.45654648956356736


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


57
[3 2 3 ... 3 3 3]
0.45787476280834916


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


58
[3 2 3 ... 3 3 3]
0.4590132827324478


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


59
[3 2 3 ... 3 3 3]
0.45749525616698294


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


60
[3 2 3 ... 3 3 3]
0.45692599620493357


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


61
[3 2 3 ... 1 3 3]
0.46091081593927896


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


62
[3 3 3 ... 1 3 3]
0.4590132827324478


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


63
[3 2 3 ... 1 3 3]
0.45920303605313095


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


64
[3 3 3 ... 3 3 3]
0.45958254269449716


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


65
[3 3 3 ... 3 3 3]
0.4616698292220114


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


66
[3 3 3 ... 1 3 3]
0.4616698292220114


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


67
[3 3 3 ... 3 3 3]
0.4612903225806452


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


68
[3 3 3 ... 3 3 3]
0.4624288425047438


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


69
[3 3 3 ... 3 3 3]
0.46110056925996207


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


70
[3 3 3 ... 3 3 3]
0.4624288425047438


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


71
[3 3 3 ... 1 3 3]
0.45977229601518027


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


72
[3 3 3 ... 1 3 3]
0.45787476280834916


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


73
[3 3 3 ... 1 3 3]
0.4573055028462998


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


74
[3 3 3 ... 1 3 3]
0.4590132827324478


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


75
[3 3 3 ... 1 3 3]
0.45958254269449716


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


76
[3 3 3 ... 1 3 3]
0.45977229601518027


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


77
[3 3 3 ... 1 3 3]
0.45806451612903226


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


78
[3 3 3 ... 3 3 3]
0.45920303605313095


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


79
[3 3 3 ... 3 3 3]
0.4603415559772296


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


80
[3 3 3 ... 3 3 3]
0.4607210626185958


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


81
[3 3 3 ... 3 3 3]
0.45977229601518027


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


82
[3 3 3 ... 3 3 3]
0.4599620493358634


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


83
[3 3 3 ... 3 3 3]
0.4586337760910816


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


84
[3 3 3 ... 1 3 3]
0.45692599620493357


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


85
[3 3 3 ... 3 3 3]
0.4601518026565465


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


86
[3 3 3 ... 3 3 3]
0.4618595825426945


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


87
[3 3 3 ... 3 3 3]
0.46110056925996207


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


88
[3 3 3 ... 3 3 3]
0.4614800759013283


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


89
[3 3 3 ... 3 3 3]
0.4618595825426945


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


90
[3 3 3 ... 3 3 3]
0.4628083491461101


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


91
[3 3 3 ... 3 3 3]
0.46261859582542697


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


92
[3 3 3 ... 3 3 3]
0.4614800759013283


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


93
[3 3 3 ... 3 3 3]
0.4616698292220114


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


94
[3 3 3 ... 3 3 3]
0.46110056925996207


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


95
[3 3 3 ... 3 3 3]
0.4586337760910816


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


96
[3 3 3 ... 3 3 3]
0.4599620493358634


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


97
[3 3 3 ... 1 3 3]
0.4605313092979127


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


98
[3 3 3 ... 3 3 3]
0.4607210626185958


C:\Users\91830\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


99
[3 3 3 ... 1 3 3]
0.46261859582542697


In [57]:
from sklearn.linear_model import LogisticRegression
lgr = LogisticRegression()
lgr.fit(X_train,y_train)

C:\Users\91830\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\91830\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [58]:
pred = lgr.predict(X_test) 
accuracy_score(y_test,pred)

0.49146110056925996